//
// Created by Pablo Lobato on 28/11/2023.
//

#ifndef JUANPABLOLOBATO_CASO_FINAL_INTEGRADOR_MAIN_H
#define JUANPABLOLOBATO_CASO_FINAL_INTEGRADOR_MAIN_H


class main {

};


#endif //JUANPABLOLOBATO_CASO_FINAL_INTEGRADOR_MAIN_H
